const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  SET_CURRENT_SUCCESS: 'SET_CURRENT_SUCCESS',
  SET_CURRENT_FAILURE: 'SET_CURRENT_FAILURE',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  EMAIL_SIGN_IN_SUCCESS: 'EMAIL_SIGN_IN_SUCCESS',
  EMAIL_SIGN_IN_FAILURE: 'EMAIL_SIGN_IN_FAILURE'
};

export default UserActionTypes;
